#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for src/backend/replication/raft
#
# IDENTIFICATION
#    src/backend/replication/raft/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/replication/raft
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	raft.o \
	raft_config.o \
	raft_log.o \
	raft_rpc.o

include $(top_srcdir)/src/backend/common.mk
