#-------------------------------------------------------------------------
#
# Makefile--
#    Makefile for access/ivfflat
#
# IDENTIFICATION
#    src/backend/access/ivfflat/Makefile
#
#-------------------------------------------------------------------------

subdir = src/backend/access/ivfflat
top_builddir = ../../../..
include $(top_builddir)/src/Makefile.global

OBJS = \
	ivfflatbuild.o \
	ivfflatcost.o \
	ivfflatinsert.o \
	ivfflatoptions.o \
	ivfflatscan.o \
	ivfflatutils.o \
	ivfflatvacuum.o \
	ivfflatvalidate.o

include $(top_srcdir)/src/backend/common.mk
